In [1]:
import pandas as pd

In [2]:
good_quad = pd.read_csv("goodQuadgram.csv")
good_tri = pd.read_csv("goodTriGrams.csv")
good_bi = pd.read_csv("goodBigram.csv")
good_uni = pd.read_csv(r"D:\ML Internship\test 2\ngrams\unigram_sorted.csv")

In [3]:
good_quad

,Unnamed: 0,4-gram,documents,total freq,avg
0,NaN,cell tumor liver cancer,529,529,1.000000
1,NaN,cancer prevention prognosis screening,529,529,1.000000
2,NaN,fat cell tumor liver,529,529,1.000000
3,NaN,prevention prognosis screening detection,529,529,1.000000
4,NaN,prognosis screening detection cancer,529,529,1.000000
5,NaN,tumor liver cancer phillip,529,529,1.000000
6,NaN,cancer fat cell tumor,526,526,1.000000
7,NaN,small cell lung cancer,92,392,4.260870
8,NaN,adolescent young adult cancer,21,99,4.714286
9,NaN,rare brain spine tumor,46,97,2.108696
10,NaN,chronic graft host disease,11,82,7.454545
11,NaN,paranasal sinus nasal cavity,5,81,16.200000
12,NaN,triple negative breast cancer,25,76,3.040000
13,NaN,cancer staging manual springer,7,74,10.571429
14,NaN,hematopoietic stem cell transplant,8,74,9.250000
15,NaN,amin edge cancer staging,7,73,10.428571
16,NaN,edge cancer staging manual,7,73,10.428571
17,NaN,receptor positive breast cancer,12,72,6.000000
18,NaN,hematopoietic stem cell transplantation,12,72,6.000000
19,NaN,anaplastic large cell lymphoma,9,71,7.888889
20,NaN,stage small cell lung,10,69,6.900000
21,NaN,sinus nasal cavity cancer,5,68,13.600000
22,NaN,cancer small cell lung,14,68,4.857143
23,NaN,series picture area body,31,68,2.193548
24,NaN,her2 positive breast cancer,13,64,4.923077
25,NaN,hereditary nonpolyposis colorectal cancer,1,61,61.000000
26,NaN,magnetic resonance imaging mri,42,58,1.380952
27,NaN,survivor adolescent young adult,2,57,28.500000
28,NaN,surgery radiation therapy chemotherapy,22,57,2.590909
29,NaN,epidermal growth factor receptor,16,55,3.437500
30,NaN,lymph node distant metastasis,6,54,9.000000
31,NaN,woman stage breast cancer,26,52,2.000000
32,NaN,advanced cancer location drug,16,51,3.187500
33,NaN,cancer location drug criterion,16,51,3.187500
34,NaN,brain spine tumor cancer,44,50,1.136364
35,NaN,lung cancer small cell,11,49,4.454545
36,NaN,squamous cell carcinoma skin,8,49,6.125000
37,NaN,atypical teratoid rhabdoid tumor,10,49,4.900000
38,NaN,regional lymph node metastasis,6,48,8.000000
39,NaN,hormone receptor positive breast,6,48,8.000000
40,NaN,factor prognosis chance recovery,22,46,2.090909
41,NaN,tumor regional lymph node,5,46,9.200000
42,NaN,annual plan budget proposal,25,45,1.800000
43,NaN,clear cell sarcoma kidney,5,45,9.000000
44,NaN,basal cell carcinoma squamous,5,44,8.800000
45,NaN,external beam radiation therapy,23,44,1.913043
46,NaN,regional lymph node distant,5,44,8.800000
47,NaN,low- middle income country,25,44,1.760000
48,NaN,description tumor regional lymph,5,43,8.600000
49,NaN,breast cancer prevention good,42,42,1.000000
50,NaN,detection genetic medicine cancer,42,42,1.000000
51,NaN,prevention detection genetic medicine,42,42,1.000000
52,NaN,cancer prevention detection genetic,42,42,1.000000
53,NaN,late cancer prevention detection,42,42,1.000000
54,NaN,prognosis chance recovery option,21,41,1.952381

In [4]:
good_tri

                         3-gram  documents  total freq        avg
0          drug genetics cancer        815         815   1.000000
1          cancer drug genetics        815         815   1.000000
2    screening detection cancer        536         536   1.000000
3               cancer fat cell        526         532   1.011407
4                fat cell tumor        529         532   1.005671
..                          ...        ...         ...        ...
235      extracranial germ cell          4          41  10.250000
236       adult cancer survivor          7          41   5.857143
237        pediatric adult rare         36          41   1.138889
238        annual status cancer         21          41   1.952381
239       lymph node dissection         14          41   2.928571

[240 rows x 4 columns]

In [5]:
good_bi = good_bi.loc[good_bi["documents"]>2]
good_uni = good_uni.loc[good_uni["documents"]>2]

In [6]:
def extractGrams(gramNo,targetGramNo,data):
    ans = []
    i = 0
    while(i<=(gramNo-targetGramNo)):
        st = ""
        for j in range(targetGramNo):
            st += data[j+i] + " "
        ans.append(st[:-1])
        i += 1
    return ans

In [7]:
tri_terms = []
bi_terms = []
uni_terms = []

for i,term in enumerate(good_quad["4-gram"]):
    term_li = term.split(" ")

    tri_li = extractGrams(4,3,term_li)
    for tri in tri_li:
        tri_terms.append((tri,i))

    bi_li = extractGrams(4,2,term_li)
    for bi in bi_li:
        bi_terms.append((bi,i))

    uni_li = extractGrams(4,1,term_li)
    for uni in uni_li:
        uni_terms.append((uni,i))

In [8]:
def remove_duplicate(data):
    seen = set()
    result = []
    for item in data:
        if item[0] not in seen:
            seen.add(item[0])
            result.append(item)
    return result

In [9]:
tri_terms = remove_duplicate(tri_terms)
bi_terms = remove_duplicate(bi_terms)
uni_terms = remove_duplicate(uni_terms)

In [10]:
for i,tri in enumerate(good_tri["3-gram"]):
    for term in tri_terms:
        if tri==term[0]:
            value = good_tri["total freq"][i] - good_quad["total freq"][term[1]]
            good_tri.loc[i,'total freq'] = value

In [11]:
good_tri

                         3-gram  documents  total freq        avg
0          drug genetics cancer        815         815   1.000000
1          cancer drug genetics        815         815   1.000000
2    screening detection cancer        536           7   1.000000
3               cancer fat cell        526           6   1.011407
4                fat cell tumor        529           3   1.005671
..                          ...        ...         ...        ...
235      extracranial germ cell          4          41  10.250000
236       adult cancer survivor          7          41   5.857143
237        pediatric adult rare         36          41   1.138889
238        annual status cancer         21          41   1.952381
239       lymph node dissection         14          41   2.928571

[240 rows x 4 columns]

In [12]:
for i, bi in enumerate(good_bi["2-gram"]):
    for term in bi_terms:
        if bi == term[0]:
            value = good_bi.loc[i, "total freq"] - good_quad.loc[term[1], "total freq"]
            good_bi.loc[i, "total freq"] = value

KeyError: 916

In [ ]:
bi_terms = []
uni_terms = []

for i,term in enumerate(good_tri["3-gram"]):
    term_li = term.split(" ")

    bi_li = extractGrams(3,2,term_li)
    for bi in bi_li:
        bi_terms.append((bi,i))

    uni_li = extractGrams(3,1,term_li)
    for uni in uni_li:
        uni_terms.append((uni,i))

In [ ]:
bi_terms = remove_duplicate(bi_terms)
uni_terms = remove_duplicate(uni_terms)